//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Logic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Ajouté !.
        /// </summary>
        internal static string ItemAdded {
            get {
                return ResourceManager.GetString("ItemAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce Champ est obligatoire !.
        /// </summary>
        internal static string Mandatory_Field_Error_Message {
            get {
                return ResourceManager.GetString("Mandatory_Field_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le prix doit avoir une valeur positive !.
        /// </summary>
        internal static string Negative_Price_Error_Message {
            get {
                return ResourceManager.GetString("Negative_Price_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le prix n&apos;est pas valide !.
        /// </summary>
        internal static string Price_Wrong_Format {
            get {
                return ResourceManager.GetString("Price_Wrong_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de pass uncorrect !.
        /// </summary>
        internal static string Wrong_Password {
            get {
                return ResourceManager.GetString("Wrong_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur uncorrect !.
        /// </summary>
        internal static string Wrong_UserName {
            get {
                return ResourceManager.GetString("Wrong_UserName", resourceCulture);
            }
        }
    }
}
